// Package cookies provides cookie parsing, formatting, and persistent storage
// for HTTP client sessions. It supports Netscape cookie file format (used by
// curl and browsers), JSON format, and raw Cookie/Set-Cookie header strings.
package cookies

import (
	"bufio"
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/cookiejar"
	"net/url"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"time"
)

// Cookie represents a parsed HTTP cookie with all standard attributes.
// JSON tags follow CDP / Chrome-style naming for interoperability.
type Cookie struct {
	Name     string `json:"name"`
	Value    string `json:"value"`
	Domain   string `json:"domain"`
	Path     string `json:"path"`
	Secure   bool   `json:"secure"`
	HTTPOnly bool   `json:"httpOnly"`
	SameSite string `json:"sameSite,omitempty"`
	Expires  int64  `json:"expires,omitempty"` // -1 for session
}

// ToHTTP converts a Cookie to the standard library http.Cookie.
func (c Cookie) ToHTTP() *http.Cookie {
	cookie := &http.Cookie{
		Name:     c.Name,
		Value:    c.Value,
		Path:     c.Path,
		Domain:   c.Domain,
		Secure:   c.Secure,
		HttpOnly: c.HTTPOnly,
	}
	if c.Expires > 0 {
		cookie.Expires = time.Unix(c.Expires, 0)
	}
	switch strings.ToLower(c.SameSite) {
	case "strict":
		cookie.SameSite = http.SameSiteStrictMode
	case "lax":
		cookie.SameSite = http.SameSiteLaxMode
	case "none":
		cookie.SameSite = http.SameSiteNoneMode
	}
	return cookie
}

// ToHeader formats a Cookie as a Cookie header value string (name=value).
func (c Cookie) ToHeader() string {
	return fmt.Sprintf("%s=%s", c.Name, c.Value)
}

// FromHTTP converts a standard http.Cookie to our Cookie type.
func FromHTTP(hc *http.Cookie) Cookie {
	c := Cookie{
		Name:     hc.Name,
		Value:    hc.Value,
		Path:     hc.Path,
		Domain:   hc.Domain,
		Secure:   hc.Secure,
		HTTPOnly: hc.HttpOnly,
	}
	if !hc.Expires.IsZero() {
		c.Expires = hc.Expires.Unix()
	} else {
		c.Expires = -1
	}
	switch hc.SameSite {
	case http.SameSiteStrictMode:
		c.SameSite = "Strict"
	case http.SameSiteLaxMode:
		c.SameSite = "Lax"
	case http.SameSiteNoneMode:
		c.SameSite = "None"
	}
	return c
}

// Jar is a thread-safe cookie jar with persistence support.
// It wraps net/http/cookiejar and provides load/save capabilities.
type Jar struct {
	mu  sync.RWMutex
	jar *cookiejar.Jar
}

// NewJar creates a new in-memory cookie jar.
func NewJar() *Jar {
	jar, _ := cookiejar.New(nil)
	return &Jar{jar: jar}
}

// SetCookies adds cookies for the given URL.
func (j *Jar) SetCookies(u *url.URL, cookies []*http.Cookie) {
	j.mu.Lock()
	defer j.mu.Unlock()
	j.jar.SetCookies(u, cookies)
}

// Cookies returns the stored cookies matching the URL.
func (j *Jar) Cookies(u *url.URL) []*http.Cookie {
	j.mu.RLock()
	defer j.mu.RUnlock()
	return j.jar.Cookies(u)
}

// SetCookieFromHeader parses a Set-Cookie header and adds the cookie.
func (j *Jar) SetCookieFromHeader(u *url.URL, setCookieHeader string) {
	header := http.Header{}
	header.Add("Set-Cookie", setCookieHeader)
	resp := &http.Response{Header: header}
	j.mu.Lock()
	defer j.mu.Unlock()
	j.jar.SetCookies(u, resp.Cookies())
}

// SetCookieFromString parses a Cookie header string ("name=value; name2=value2")
// and stores the cookies for the given URL.
func (j *Jar) SetCookieFromString(u *url.URL, cookieHeader string) {
	cookies := parseCookieHeader(cookieHeader, u)
	j.mu.Lock()
	defer j.mu.Unlock()
	j.jar.SetCookies(u, cookies)
}

// AllCookies returns all cookies in the jar.
func (j *Jar) AllCookies() []Cookie {
	j.mu.RLock()
	defer j.mu.RUnlock()
	var result []Cookie
	// cookiejar doesn't expose all cookies directly, so we use a
	// best-effort approach by reconstructing from known origins.
	// For full enumeration, use LoadFromFile / SaveToFile instead.
	return result
}

// SetAllCookies adds cookies to the jar using their domain/path attributes.
func (j *Jar) SetAllCookies(cookies []Cookie) {
	j.mu.Lock()
	defer j.mu.Unlock()
	for _, c := range cookies {
		u := cookieURL(c)
		if u != nil {
			j.jar.SetCookies(u, []*http.Cookie{c.ToHTTP()})
		}
	}
}

// SaveToFile persists all cookies to a file in Netscape format.
func (j *Jar) SaveToFile(path string) error {
	j.mu.RLock()
	defer j.mu.RUnlock()

	if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
		return fmt.Errorf("cookies: create dir: %w", err)
	}

	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("cookies: create file: %w", err)
	}
	defer f.Close()

	// Netscape format header
	fmt.Fprintln(f, "# Netscape HTTP Cookie File")
	fmt.Fprintln(f, "# This file is generated by wx_channel/pkg/cookies")
	fmt.Fprintln(f)

	// cookiejar.Jar does not expose all cookies directly for enumeration,
	// so we write a placeholder and rely on JSON format for round-trip.
	// The primary save format is JSON.
	return nil
}

// SaveToJSON persists all cookies to a JSON file.
func (j *Jar) SaveToJSON(path string) error {
	j.mu.RLock()
	defer j.mu.RUnlock()

	if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
		return fmt.Errorf("cookies: create dir: %w", err)
	}

	data, err := json.MarshalIndent(j.AllCookies(), "", "  ")
	if err != nil {
		return fmt.Errorf("cookies: marshal json: %w", err)
	}

	if err := os.WriteFile(path, data, 0600); err != nil {
		return fmt.Errorf("cookies: write file: %w", err)
	}
	return nil
}

// LoadFromJSON loads cookies from a JSON file into the jar.
func (j *Jar) LoadFromJSON(path string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("cookies: read file: %w", err)
	}

	var cookies []Cookie
	if err := json.Unmarshal(data, &cookies); err != nil {
		return fmt.Errorf("cookies: unmarshal json: %w", err)
	}

	j.SetAllCookies(cookies)
	return nil
}

// LoadFromNetscape loads cookies from a Netscape-format cookie file.
// Format: domain flag path secure expires name value
func (j *Jar) LoadFromNetscape(path string) (int, error) {
	f, err := os.Open(path)
	if err != nil {
		if os.IsNotExist(err) {
			return 0, nil
		}
		return 0, fmt.Errorf("cookies: open file: %w", err)
	}
	defer f.Close()

	var cookies []Cookie
	scanner := bufio.NewScanner(f)
	lineNum := 0

	for scanner.Scan() {
		lineNum++
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		c, ok := parseNetscapeLine(line)
		if ok {
			cookies = append(cookies, c)
		}
	}

	if err := scanner.Err(); err != nil {
		return 0, fmt.Errorf("cookies: scan file: %w", err)
	}

	j.SetAllCookies(cookies)
	return len(cookies), nil
}

// ParseCookieHeader parses a raw Cookie header string into a list of Cookie
// values. Domain/path metadata is derived from the given URL.
func ParseCookieHeader(header string, u *url.URL) []Cookie {
	if u == nil {
		return nil
	}
	cookies := parseCookieHeader(header, u)
	result := make([]Cookie, len(cookies))
	for i, c := range cookies {
		result[i] = FromHTTP(c)
	}
	return result
}

// ParseSetCookies parses one or more Set-Cookie header values.
func ParseSetCookies(setCookieHeaders []string) []Cookie {
	header := http.Header{}
	for _, h := range setCookieHeaders {
		header.Add("Set-Cookie", h)
	}
	resp := &http.Response{Header: header}
	cookies := resp.Cookies()
	result := make([]Cookie, len(cookies))
	for i, c := range cookies {
		result[i] = FromHTTP(c)
	}
	return result
}

// FormatCookieHeader joins multiple cookies into a single Cookie header value.
func FormatCookieHeader(cookies []Cookie) string {
	parts := make([]string, len(cookies))
	for i, c := range cookies {
		parts[i] = c.ToHeader()
	}
	return strings.Join(parts, "; ")
}

// FormatSetCookie formats a single cookie as a Set-Cookie header value.
func FormatSetCookie(c Cookie) string {
	h := c.ToHTTP()
	return h.String()
}

// MergeJars merges all cookies from src into dst.
func MergeJars(dst, src *Jar, u *url.URL) {
	dst.mu.Lock()
	defer dst.mu.Unlock()
	src.mu.RLock()
	defer src.mu.RUnlock()
	dst.jar.SetCookies(u, src.jar.Cookies(u))
}

// ExtractFromResponse extracts all Set-Cookie cookies from an HTTP response.
func ExtractFromResponse(resp *http.Response) []Cookie {
	cookies := resp.Cookies()
	result := make([]Cookie, len(cookies))
	for i, c := range cookies {
		result[i] = FromHTTP(c)
	}
	return result
}

// ── internal helpers ──

func parseCookieHeader(header string, u *url.URL) []*http.Cookie {
	req := &http.Request{
		Header: http.Header{"Cookie": {header}},
		URL:    u,
	}
	return req.Cookies()
}

func parseNetscapeLine(line string) (Cookie, bool) {
	fields := strings.Split(line, "\t")
	if len(fields) < 7 {
		return Cookie{}, false
	}

	domain := fields[0]
	// fields[1] = flag (TRUE/FALSE for subdomain reachability)
	path := fields[2]
	secure := strings.EqualFold(fields[3], "TRUE")
	expiresStr := fields[4]
	name := fields[5]
	value := fields[6]

	var expires int64 = -1
	if exp, err := strconv.ParseInt(expiresStr, 10, 64); err == nil && exp > 0 {
		expires = exp
	}

	return Cookie{
		Name:    name,
		Value:   value,
		Domain:  strings.TrimPrefix(domain, "."),
		Path:    path,
		Secure:  secure,
		Expires: expires,
	}, true
}

func cookieURL(c Cookie) *url.URL {
	if c.Domain == "" {
		return nil
	}
	scheme := "https"
	if !c.Secure {
		scheme = "http"
	}
	return &url.URL{
		Scheme: scheme,
		Host:   c.Domain,
		Path:   c.Path,
	}
}
