import js from "@eslint/js";
import globals from "globals";

export default [
  {
    ignores: ["public/**", "docs/**", "dist/**", "node_modules/**"],
  },
  {
    files: ["src/**/*.js", "hub/admin/public/app.js", "hub/admin/functions/**/*.js"],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: "module",
      globals: {
        ...globals.browser,
        Timeless: "readonly",
        Fragment: "readonly",
        Button: "readonly",
        IconButton: "readonly",
        Input: "readonly",
        Textarea: "readonly",
        Select: "readonly",
        Checkbox: "readonly",
        Img: "readonly",
        LazyImg: "readonly",
        Link: "readonly",
        Dialog: "readonly",
        Drawer: "readonly",
        DialogHeader: "readonly",
        DialogTitle: "readonly",
        DialogDescription: "readonly",
        DialogBody: "readonly",
        DialogFooter: "readonly",
        Popover: "readonly",
        DropdownMenu: "readonly",
        Dropdown: "readonly",
        Pagination: "readonly",
        Label: "readonly",
        Badge: "readonly",
        Card: "readonly",
        CardHeader: "readonly",
        CardTitle: "readonly",
        CardDescription: "readonly",
        CardContent: "readonly",
        CardFooter: "readonly",
        Table: "readonly",
        TableHeader: "readonly",
        TableBody: "readonly",
        TableRow: "readonly",
        TableHead: "readonly",
        TableCell: "readonly",
        Skeleton: "readonly",
        Progress: "readonly",
        Separator: "readonly",
        Alert: "readonly",
        AlertTitle: "readonly",
        AlertDescription: "readonly",
        ErrorFallbackView: "readonly",
        LoadingView: "readonly",
        createInputStore: "readonly",
        DL: "readonly",
        dl$: "readonly",
        DownloadTaskModel: "readonly",
        DownloaderModel: "readonly",
        DLUtils: "readonly",
        VirtualListView: "readonly",
        isElement: "readonly",
        For: "readonly",
        Show: "readonly",
        Switch: "readonly",
        Match: "readonly",
        AspectRatio: "readonly",
        View: "readonly",
        Txt: "readonly",
        SVG: "readonly",
        Circle: "readonly",
        ref: "readonly",
        refarr: "readonly",
        refobj: "readonly",
        computed: "readonly",
        combine: "readonly",
      },
    },
    rules: {
      ...js.configs.recommended.rules,
      "no-undef": "error",
      "no-unused-vars": "warn",
      "no-console": "off",
      "no-redeclare": "off",
    },
  },
];
