import js from "@eslint/js";
import globals from "globals";

export default [
  {
    ignores: ["lib/**", "docs/**", "dist/**", "node_modules/**"],
  },
  {
    files: ["src/**/*.js"],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: "module",
      globals: {
        ...globals.browser,
        __wx_channels_store__: "writable",
        __wx_channels_tip__: "writable",
        __wx_channels_config__: "writable",
        __wx_channels_env__: "writable",
        __wx_channels_cur_video: "writable",
        __wx_asset_url: "writable",
        __wx_username: "writable",
        __wx_channels_live_store__: "writable",
        __wx_channels_version__: "writable",
        WXVariable: "writable",
        WXEnv: "writable",
        getFeedInfo: "writeable",
        WXU: "writable",
        WXE: "writable",
        render_extra_menu_items: "writable",
        LocalApiServerProtocol: "writeable",
        WSServerProtocol: "writeable",
        APIServerProtocol: "writeable",
        FakeAPIServerAddr: "writeable",
        isWin: "readonly",
        FakeLocalAPIServerAddr: "readonly",
        FakeRemoteAPIServerAddr: "readonly",
        FakeOfficialAccountServerAddr: "writeable",
        Icons: "writable",
        EventBus: "writable",
        Module: "readonly",
        saveAs: "readonly",
        JSZip: "readonly",
        PageSpy: "readonly",
        Recorder: "readonly",
        mitt: "readonly",
        Timeless: "readonly",
        Fragment: "readonly",
        Dialog: "readonly",
        Popover: "readonly",
        DropdownMenu: "readonly",
        OverwriteDownloadConfirmDialog: "readonly",
        TaskDeleteConfirmDialog: "readonly",
        ClearTasksConfirmDialog: "readonly",
        CreateDownloadTaskDialog: "readonly",
        DownloaderPanelViewModel: "readonly",
        DownloaderPanelView: "readonly",
        DownloadTaskListView: "readonly",
        VirtualListView: "readonly",
        DOWNLOAD_STATUS_COUNT_ITEMS: "readonly",
        normalize_download_status_counts: "readonly",
        get_download_status_count: "readonly",
        isElement: "readonly",
        For: "readonly",
        Show: "readonly",
        Switch: "readonly",
        Match: "readonly",
        AspectRatio: "readonly",
        View: "readonly",
        Txt: "readonly",
        SVG: "readonly",
        Circle: "readonly",
        ref: "readonly",
        refarr: "readonly",
        refobj: "readonly",
        computed: "readonly",
        combine: "readonly",
      },
    },
    rules: {
      ...js.configs.recommended.rules,
      "no-undef": "error",
      "no-unused-vars": "warn",
      "no-console": "off",
      "no-redeclare": "off",
    },
  },
];
