import js from "@eslint/js";
import globals from "globals";
import { globals as timelessGlobals } from "@timeless/dev/eslint";

export default [
  {
    ignores: ["lib/**", "docs/**", "dist/**", "node_modules/**"],
  },
  {
    files: ["src/**/*.js"],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: "script",
      globals: {
        ...globals.browser,
        ...timelessGlobals,
        __wx_channels_store__: "writable",
        __wx_channels_tip__: "writable",
        __wx_channels_config__: "writable",
        __wx_channels_cur_video: "writable",
        __wx_download_btn_handler: "writable",
        __wx_channels_decrypt: "writable",
        __wx_channels_video_decrypt: "writable",
        __wx_channels_download: "writable",
        __wx_channels_download2: "writable",
        __wx_channels_download3: "writable",
        __wx_channels_download4: "writable",
        __wx_channels_handle_click_download__: "writable",
        __wx_channels_handle_print_download_command: "writable",
        __wx_channels_handle_download_cover: "writable",
        __wx_channels_handle_copy__: "writable",
        __wx_channels_live_store__: "writable",
        __wx_channels_live_download_btn__: "writable",
        __wx_channels_version__: "writable",
        __wx_attach_download_dropdown_menu: "writeable",
        __wx_channels_live_store__: "writeable",
        __wx_refresh_downloader: "writable",
        WXVariable: "writable",
        WXU: "writable",
        WXE: "writable",
        render_extra_menu_items: "writable",
        LocalApiServerProtocol: "writeable",
        WSServerProtocol: "writeable",
        APIServerProtocol: "writeable",
        FakeAPIServerAddr: "writeable",
        FakeLocalAPIServerAddr: "readonly",
        FakeRemoteAPIServerAddr: "readonly",
        FakeOfficialAccountServerAddr: "writeable",
        insert_channels_style: "writeable",
        MoreIcon: "writeable",
        FileIcon: "writeable",
        MP3Icon: "writeable",
        MP4Icon: "writeable",
        ImageIcon: "writeable",
        FolderIcon: "writeable",
        ExternalLinkIcon: "writeable",
        PauseIcon: "writeable",
        PlayIcon: "writeable",
        RetryIcon: "writeable",
        DeleteIcon: "writeable",
        download_icon1: "writable",
        download_icon2: "writable",
        download_icon3: "writable",
        download_icon4: "writable",
        DownloadIcon5: "writable",
        DownloadIcon6: "writable",
        DownloadIcon7: "writable",
        DownloadIcon8: "writable",
        RSSIcon: "writeable",
        download_btn1: "writable",
        download_btn2: "writable",
        download_btn3: "writable",
        download_btn4: "writable",
        download_btn5: "writable",
        download_btn6: "writable",
        download_btn7: "writable",
        EventBus: "writable",
        Module: "readonly",
        saveAs: "readonly",
        JSZip: "readonly",
        PageSpy: "readonly",
        Recorder: "readonly",
        mitt: "readonly",
        Weui: "readonly",
        weui: "readonly",
        WUI: "readonly",
      },
    },
    rules: {
      ...js.configs.recommended.rules,
      "no-undef": "error",
      "no-unused-vars": "warn",
      "no-console": "off",
      "no-redeclare": "off",
    },
  },
];
