import js from "@eslint/js";
import globals from "globals";

export default [
  {
    ignores: ["lib/**", "docs/**", "dist/**", "node_modules/**"],
  },
  {
    files: ["src/**/*.js"],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: "script",
      globals: {
        ...globals.browser,
        __wx_channels_store__: "writable",
        __wx_channels_tip__: "writable",
        __wx_channels_config__: "writable",
        __wx_channels_env__: "writable",
        __wx_channels_cur_video: "writable",
        __wx_download_btn_handler: "writable",
        __wx_channels_decrypt: "writable",
        __wx_channels_video_decrypt: "writable",
        __wx_asset_url: "writable",
        __wx_username: "writable",
        __wx_channels_download2: "writable",
        __wx_channels_handle_copy__: "writable",
        __wx_channels_live_store__: "writable",
        __wx_channels_live_download_btn__: "writable",
        __wx_channels_version__: "writable",
        __wx_attach_download_dropdown_menu: "writeable",
        WXVariable: "writable",
        WXEnv: "writable",
        getFeedInfo: "writeable",
        WXU: "writable",
        WXE: "writable",
        render_extra_menu_items: "writable",
        LocalApiServerProtocol: "writeable",
        WSServerProtocol: "writeable",
        APIServerProtocol: "writeable",
        FakeAPIServerAddr: "writeable",
        isWin: "readonly",
        FakeLocalAPIServerAddr: "readonly",
        FakeRemoteAPIServerAddr: "readonly",
        FakeOfficialAccountServerAddr: "writeable",
        MoreIcon: "writeable",
        FileIcon: "writeable",
        MP3Icon: "writeable",
        MP4Icon: "writeable",
        ImageIcon: "writeable",
        FolderIcon: "writeable",
        ExternalLinkIcon: "writeable",
        PauseIcon: "writeable",
        PlayIcon: "writeable",
        RetryIcon: "writeable",
        DeleteIcon: "writeable",
        download_icon1: "writable",
        download_icon2: "writable",
        download_icon3: "writable",
        download_icon4: "writable",
        DownloadIcon5: "writable",
        DownloadIcon6: "writable",
        DownloadIcon7: "writable",
        DownloadIcon8: "writable",
        RSSIcon: "writeable",
        download_btn1: "writable",
        download_btn2: "writable",
        download_btn3: "writable",
        download_btn4: "writable",
        download_btn5: "writable",
        download_btn7: "writable",
        __wx_refresh_downloader: "writable",
        EventBus: "writable",
        Module: "readonly",
        saveAs: "readonly",
        JSZip: "readonly",
        PageSpy: "readonly",
        Recorder: "readonly",
        mitt: "readonly",
        Timeless: "readonly",
        Fragment: "readonly",
        Dialog: "readonly",
        Popover: "readonly",
        DropdownMenu: "readonly",
        OverwriteDownloadConfirmDialog: "readonly",
        TaskDeleteConfirmDialog: "readonly",
        ClearTasksConfirmDialog: "readonly",
        CreateDownloadTaskDialog: "readonly",
        DownloaderPanelViewModel: "readonly",
        DownloaderPanelView: "readonly",
        DownloadTaskListView: "readonly",
        VirtualListView: "readonly",
        DOWNLOAD_STATUS_COUNT_ITEMS: "readonly",
        normalize_download_status_counts: "readonly",
        get_download_status_count: "readonly",
        isElement: "readonly",
        For: "readonly",
        Show: "readonly",
        Switch: "readonly",
        Match: "readonly",
        View: "readonly",
        Txt: "readonly",
        SVG: "readonly",
        Circle: "readonly",
        ref: "readonly",
        refarr: "readonly",
        refobj: "readonly",
        computed: "readonly",
        combine: "readonly",
      },
    },
    rules: {
      ...js.configs.recommended.rules,
      "no-undef": "error",
      "no-unused-vars": "warn",
      "no-console": "off",
      "no-redeclare": "off",
    },
  },
];
