package novelsource

var (
	numericBookPatterns = []URLPattern{
		{Expr: `^/(\d+)/?$`, Canonical: `/$1/`, BookID: `$1`},
		{Expr: `^/(\d+)/(\d+)/?$`, Canonical: `/$1/$2/`, BookIDJoin: `$1/$2`},
	}
	numericChapterPatterns = []URLPattern{
		{Expr: `^/(\d+)/(\d+)\.html$`, Canonical: `/$1/$2.html`, BookID: `$1`, ChapterID: `$2`},
		{Expr: `^/(\d+)/(\d+)/([^/]+)\.html$`, Canonical: `/$1/$2/$3.html`, BookIDJoin: `$1/$2`, ChapterID: `$3`},
	}
	commonBookPatterns = []URLPattern{
		{Expr: `^/book/([^/.]+)/?$`, Canonical: `/book/$1/`, BookID: `$1`},
		{Expr: `^/book/([^/.]+)\.html$`, Canonical: `/book/$1.html`, BookID: `$1`},
		{Expr: `^/newbook/([^/.]+)/?$`, Canonical: `/newbook/$1/`, BookID: `$1`},
		{Expr: `^/info/([^/.]+)\.html$`, Canonical: `/info/$1.html`, BookID: `$1`},
	}
	commonChapterPatterns = []URLPattern{
		{Expr: `^/book/([^/]+)/([^/]+)\.html$`, Canonical: `/book/$1/$2.html`, BookID: `$1`, ChapterID: `$2`},
		{Expr: `^/chapter/([^/]+)/([^/]+)\.html$`, Canonical: `/chapter/$1/$2.html`, BookID: `$1`, ChapterID: `$2`},
		{Expr: `^/read/([^/]+)/([^/]+)\.html$`, Canonical: `/read/$1/$2.html`, BookID: `$1`, ChapterID: `$2`},
	}
	biqugeLikeCatalogSelectors = []string{
		"#list > dl > dd > a",
		"#list dd a",
		"dl > dt:nth-of-type(2) ~ dd > a",
	}
)

var registeredSources = []Source{
	{
		ID:                    "xbiqugu",
		Name:                  "香书小说",
		BaseURL:               "http://www.xbiqugu.la",
		BookPatterns:          patterns(numericBookPatterns, commonBookPatterns),
		ChapterPatterns:       patterns(numericChapterPatterns, commonChapterPatterns),
		CatalogSelectors:      biqugeLikeCatalogSelectors,
		SampleNovelURL:        "http://www.xbiqugu.la/0/951/",
		SampleChapterURL:      "http://www.xbiqugu.la/0/951/217034.html",
		ChapterTitleSelectors: []string{".bookname > h1"},
	},
	{
		ID:               "shuhaige",
		Name:             "书海阁小说网",
		BaseURL:          "https://www.shuhaige.net",
		BookPatterns:     patterns(numericBookPatterns),
		ChapterPatterns:  patterns(numericChapterPatterns),
		CatalogSelectors: []string{"dl > dt:nth-of-type(2) ~ dd > a", "#list dd a"},
		SampleNovelURL:   "https://www.shuhaige.net/372421/",
		SampleChapterURL: "https://www.shuhaige.net/372421/128630527.html",
	},
	{
		ID:                    "mcxs",
		Name:                  "梦书中文",
		BaseURL:               "http://www.mcxs.info",
		BookPatterns:          patterns(commonBookPatterns, numericBookPatterns),
		ChapterPatterns:       patterns(commonChapterPatterns, numericChapterPatterns),
		CatalogSelectors:      biqugeLikeCatalogSelectors,
		SampleNovelURL:        "http://www.mcxs.info/book/1/",
		SampleChapterURL:      "http://www.mcxs.info/book/1/2.html",
		ChapterTitleSelectors: []string{".bookname > h1"},
	},
	{
		ID:               "99xs",
		Name:             "鸟书网",
		BaseURL:          "http://www.99xs.info",
		BookPatterns:     patterns(commonBookPatterns, numericBookPatterns),
		ChapterPatterns:  patterns(commonChapterPatterns, numericChapterPatterns),
		CatalogSelectors: []string{"dl > dt:nth-of-type(2) ~ dd > a", "#list dd a"},
		SampleNovelURL:   "http://www.99xs.info/book/1/",
		SampleChapterURL: "http://www.99xs.info/book/1/2.html",
	},
	{
		ID:               "22biqu",
		Name:             "笔趣阁22",
		BaseURL:          "https://www.22biqu.com",
		BookPatterns:     patterns(commonBookPatterns, numericBookPatterns),
		ChapterPatterns:  patterns(commonChapterPatterns, numericChapterPatterns),
		CatalogSelectors: []string{"div:nth-child(4) > ul > li > a", "#list dd a"},
		SampleNovelURL:   "https://www.22biqu.com/book/1/",
		SampleChapterURL: "https://www.22biqu.com/book/1/2.html",
	},
	{
		ID:      "xbiquzw",
		Name:    "笔尖中文",
		BaseURL: "http://www.xbiquzw.net",
		BookPatterns: patterns([]URLPattern{
			{Expr: `^/([^/.]+)/?$`, Canonical: `/$1/`, BookID: `$1`},
		}, commonBookPatterns, numericBookPatterns),
		ChapterPatterns: patterns([]URLPattern{
			{Expr: `^/([^/.]+)/([^/]+)\.html$`, Canonical: `/$1/$2.html`, BookID: `$1`, ChapterID: `$2`},
		}, commonChapterPatterns, numericChapterPatterns),
		CatalogSelectors: biqugeLikeCatalogSelectors,
		SampleNovelURL:   "http://www.xbiquzw.net/1/",
		SampleChapterURL: "http://www.xbiquzw.net/1/2.html",
	},
	{
		ID:               "shu009",
		Name:             "书林文学",
		BaseURL:          "http://www.shu009.com",
		BookPatterns:     patterns(commonBookPatterns, numericBookPatterns),
		ChapterPatterns:  patterns(commonChapterPatterns, numericChapterPatterns),
		CatalogTemplates: []string{"/indexlist/%s/"},
		CatalogSelectors: []string{"ol > li > a", "#list dd a"},
		SampleNovelURL:   "http://www.shu009.com/book/1/",
		SampleChapterURL: "http://www.shu009.com/book/1/2.html",
	},
	{
		ID:               "ujxsw",
		Name:             "悠久小说网",
		BaseURL:          "http://www.ujxsw.org",
		BookPatterns:     patterns(commonBookPatterns, numericBookPatterns),
		ChapterPatterns:  patterns(commonChapterPatterns, numericChapterPatterns),
		CatalogSelectors: biqugeLikeCatalogSelectors,
		SampleNovelURL:   "http://www.ujxsw.org/book/1/",
		SampleChapterURL: "http://www.ujxsw.org/book/1/2.html",
	},
	{
		ID:               "yeudusk",
		Name:             "阅读库",
		BaseURL:          "http://www.yeudusk.com",
		BookPatterns:     patterns(commonBookPatterns, numericBookPatterns),
		ChapterPatterns:  patterns(commonChapterPatterns, numericChapterPatterns),
		CatalogSelectors: biqugeLikeCatalogSelectors,
		SampleNovelURL:   "http://www.yeudusk.com/book/1/",
		SampleChapterURL: "http://www.yeudusk.com/book/1/2.html",
	},
	{
		ID:               "wxsy",
		Name:             "顶点小说",
		BaseURL:          "https://www.wxsy.net",
		BookPatterns:     patterns(commonBookPatterns, numericBookPatterns),
		ChapterPatterns:  patterns(commonChapterPatterns, numericChapterPatterns),
		CatalogSelectors: biqugeLikeCatalogSelectors,
		SampleNovelURL:   "https://www.wxsy.net/book/1/",
		SampleChapterURL: "https://www.wxsy.net/book/1/2.html",
	},
	{
		ID:      "biquge365",
		Name:    "笔趣阁365",
		BaseURL: "https://www.biquge365.net",
		BookPatterns: patterns([]URLPattern{
			{Expr: `^/newbook/([^/.]+)/?$`, Canonical: `/newbook/$1/`, BookID: `$1`},
			{Expr: `^/book/([^/.]+)/?$`, Canonical: `/book/$1/`, BookID: `$1`},
		}, commonBookPatterns),
		ChapterPatterns:  patterns(commonChapterPatterns),
		CatalogSelectors: []string{"#list a", ".listmain a", "dl dd a"},
		SampleNovelURL:   "https://www.biquge365.net/newbook/39884/",
		SampleChapterURL: "https://www.biquge365.net/chapter/39884/69449442.html",
	},
	{
		ID:               "ranwen8",
		Name:             "燃文小说网",
		BaseURL:          "https://www.ranwen8.cc",
		BookPatterns:     patterns(commonBookPatterns, numericBookPatterns),
		ChapterPatterns:  patterns(commonChapterPatterns, numericChapterPatterns),
		CatalogSelectors: biqugeLikeCatalogSelectors,
		SampleNovelURL:   "https://www.ranwen8.cc/book/1/",
		SampleChapterURL: "https://www.ranwen8.cc/book/1/2.html",
	},
	{
		ID:      "69shuba",
		Name:    "69书吧",
		BaseURL: "https://www.69shuba.com",
		BookPatterns: []URLPattern{
			{Expr: `^/book/([^/.]+)\.htm$`, Canonical: `/book/$1.htm`, BookID: `$1`},
			{Expr: `^/book/([^/.]+)/?$`, Canonical: `/book/$1/`, BookID: `$1`},
		},
		ChapterPatterns: []URLPattern{
			{Expr: `^/txt/([^/]+)/([^/.]+)(?:\.html?)?$`, Canonical: `/txt/$1/$2`, BookID: `$1`, ChapterID: `$2`},
			{Expr: `^/book/([^/]+)/([^/.]+)\.html?$`, Canonical: `/book/$1/$2.html`, BookID: `$1`, ChapterID: `$2`},
		},
		CatalogTemplates: []string{"/book/%s/"},
		CatalogSelectors: []string{"#catalog > ul > li > a", ".qustime li a"},
		SampleNovelURL:   "https://www.69shuba.com/book/34567.htm",
		SampleChapterURL: "https://www.69shuba.com/txt/34567/41064442",
	},
	{
		ID:      "quanben5",
		Name:    "全本小说网",
		BaseURL: "https://quanben5.com",
		BookPatterns: []URLPattern{
			{Expr: `^/n/([^/]+)/?$`, Canonical: `/n/$1/`, BookID: `$1`},
		},
		ChapterPatterns: []URLPattern{
			{Expr: `^/n/([^/]+)/([^/.]+)\.html$`, Canonical: `/n/$1/$2.html`, BookID: `$1`, ChapterID: `$2`},
		},
		CatalogTemplates: []string{"/n/%s/xiaoshuo.html"},
		CatalogSelectors: []string{"ul > li > a", ".chapter a"},
		SampleNovelURL:   "https://quanben5.com/n/xinghedadi/",
		SampleChapterURL: "https://quanben5.com/n/xinghedadi/29882.html",
	},
	{
		ID:      "dxmwx",
		Name:    "大熊猫文学",
		BaseURL: "https://www.dxmwx.org",
		BookPatterns: []URLPattern{
			{Expr: `^/book/([^/.]+)\.html$`, Canonical: `/book/$1.html`, BookID: `$1`},
		},
		ChapterPatterns: patterns([]URLPattern{
			{Expr: `^/chapter/([^/]+)/([^/.]+)\.html$`, Canonical: `/chapter/$1/$2.html`, BookID: `$1`, ChapterID: `$2`},
			{Expr: `^/read/([^/]+)/([^/.]+)\.html$`, Canonical: `/read/$1/$2.html`, BookID: `$1`, ChapterID: `$2`},
		}, commonChapterPatterns),
		CatalogTemplates:        []string{"/chapter/%s.html"},
		CatalogSelectors:        []string{"#ListContents a", "div:nth-child(2n+5) > span > a"},
		ChapterContentSelectors: []string{"#Lab_Contents"},
		SampleNovelURL:          "https://www.dxmwx.org/book/1.html",
		SampleChapterURL:        "https://www.dxmwx.org/chapter/1/2.html",
	},
	{
		ID:      "101kks",
		Name:    "101看书",
		BaseURL: "https://101kks.com",
		BookPatterns: []URLPattern{
			{Expr: `^/book/([^/.]+)\.html$`, Canonical: `/book/$1.html`, BookID: `$1`},
		},
		ChapterPatterns: []URLPattern{
			{Expr: `^/book/([^/]+)/([^/.]+)\.html$`, Canonical: `/book/$1/$2.html`, BookID: `$1`, ChapterID: `$2`},
		},
		CatalogTemplates:        []string{"/ajax_novels/chapterlist/%s.html"},
		CatalogSelectors:        []string{"body > ul > li > a", "#catalog a"},
		ChapterTitleSelectors:   []string{".txtnav > h1"},
		ChapterContentSelectors: []string{"#txtcontent", ".txtnav"},
		SampleNovelURL:          "https://101kks.com/book/1.html",
		SampleChapterURL:        "https://101kks.com/book/1/2.html",
	},
	{
		ID:               "tianxibook",
		Name:             "新天禧小说",
		BaseURL:          "https://www.tianxibook.com",
		BookPatterns:     patterns(commonBookPatterns, numericBookPatterns),
		ChapterPatterns:  patterns(commonChapterPatterns, numericChapterPatterns),
		CatalogTemplates: []string{"/xiaoshuo/%s/"},
		CatalogSelectors: []string{"#content_1 > a", "#list a"},
		SampleNovelURL:   "https://www.tianxibook.com/book/1/",
		SampleChapterURL: "https://www.tianxibook.com/book/1/2.html",
	},
	{
		ID:      "0xs",
		Name:    "零点小说",
		BaseURL: "https://www.0xs.net",
		BookPatterns: []URLPattern{
			{Expr: `^/txt_1/([^/.]+)\.html$`, Canonical: `/txt_1/$1.html`, BookID: `$1`},
			{Expr: `^/txt/([^/.]+)\.html$`, Canonical: `/txt/$1.html`, BookID: `$1`},
		},
		ChapterPatterns: []URLPattern{
			{Expr: `^/txt_1/([^/]+)/([^/.]+)\.html$`, Canonical: `/txt_1/$1/$2.html`, BookID: `$1`, ChapterID: `$2`},
			{Expr: `^/txt/([^/]+)/([^/.]+)\.html$`, Canonical: `/txt/$1/$2.html`, BookID: `$1`, ChapterID: `$2`},
		},
		CatalogTemplates: []string{"/la_1/%s.html"},
		CatalogSelectors: []string{".catalog > div > ul > li > a", "#list a"},
		SampleNovelURL:   "https://www.0xs.net/txt_1/86276.html",
		SampleChapterURL: "https://www.0xs.net/txt_1/86276/752.html",
	},
	{
		ID:      "laoyaoxs",
		Name:    "老幺小说网",
		BaseURL: "https://www.laoyaoxs.org",
		BookPatterns: []URLPattern{
			{Expr: `^/info/([^/.]+)\.html$`, Canonical: `/info/$1.html`, BookID: `$1`},
		},
		ChapterPatterns: patterns([]URLPattern{
			{Expr: `^/chapter/([^/]+)/([^/.]+)\.html$`, Canonical: `/chapter/$1/$2.html`, BookID: `$1`, ChapterID: `$2`},
		}, commonChapterPatterns),
		CatalogTemplates:        []string{"/list/%s/"},
		CatalogSelectors:        []string{"#chapters > a"},
		ChapterTitleSelectors:   []string{"#chapter-name > h2"},
		ChapterContentSelectors: []string{"#txt"},
		SampleNovelURL:          "https://www.laoyaoxs.org/info/1.html",
		SampleChapterURL:        "https://www.laoyaoxs.org/chapter/1/2.html",
	},
	{
		ID:                      "sudugu",
		Name:                    "速读谷",
		BaseURL:                 "https://www.sudugu.org",
		BookPatterns:            patterns(numericBookPatterns),
		ChapterPatterns:         patterns(numericChapterPatterns),
		CatalogSelectors:        []string{"#list > ul > li > a", "#list a"},
		ChapterTitleSelectors:   []string{".submenu > h1"},
		ChapterContentSelectors: []string{".con"},
		SampleNovelURL:          "https://www.sudugu.org/51/",
		SampleChapterURL:        "https://www.sudugu.org/51/3194.html",
	},
	{
		ID:                      "xiaoshuohu",
		Name:                    "小说虎",
		BaseURL:                 "https://www.xiaoshuohu.com",
		BookPatterns:            patterns(numericBookPatterns),
		ChapterPatterns:         patterns(numericChapterPatterns),
		CatalogSelectors:        biqugeLikeCatalogSelectors,
		ChapterTitleSelectors:   []string{".bookname > h1"},
		ChapterContentSelectors: []string{"#content"},
		SampleNovelURL:          "https://www.xiaoshuohu.com/94247/94247982/",
		SampleChapterURL:        "https://www.xiaoshuohu.com/94247/94247982/1.html",
	},
	{
		ID:      "ttkan",
		Name:    "天天看小说",
		BaseURL: "https://cn.ttkan.co",
		Hosts:   []string{"cn.ttkan.co", "www.ttkan.co", "tw.ttkan.co"},
		BookPatterns: []URLPattern{
			{Expr: `^/novel/chapters/([^/]+)/?$`, Canonical: `/novel/chapters/$1`, BookID: `$1`},
		},
		ChapterPatterns: []URLPattern{
			{Expr: `^/novel/pagea?/([^_]+)_(\d+)\.html$`, Canonical: `/novel/pagea/$1_$2.html`, BookID: `$1`, ChapterID: `$2`},
		},
		CatalogSelectors:        []string{".full_chapters > div:nth-child(1) > a", ".full_chapters a"},
		ChapterTitleSelectors:   []string{".title > h1"},
		ChapterContentSelectors: []string{"div.content"},
		SampleNovelURL:          "https://cn.ttkan.co/novel/chapters/wanxiangzhiwang-tiancantudou",
		SampleChapterURL:        "https://cn.ttkan.co/novel/pagea/wanxiangzhiwang-tiancantudou_1.html",
	},
	{
		ID:      "xszj",
		Name:    "小说之家",
		BaseURL: "https://xszj.org",
		BookPatterns: []URLPattern{
			{Expr: `^/b/([^/]+)/?$`, Canonical: `/b/$1`, BookID: `$1`},
		},
		ChapterPatterns: []URLPattern{
			{Expr: `^/b/([^/]+)/c/([^/]+)$`, Canonical: `/b/$1/c/$2`, BookID: `$1`, ChapterID: `$2`},
		},
		CatalogTemplates:        []string{"/b/%s/cs/1"},
		CatalogSelectors:        []string{"#content_1 > a", "article a"},
		ChapterTitleSelectors:   []string{"#wrapper > article > h1"},
		ChapterContentSelectors: []string{"#booktxt", "article"},
		SampleNovelURL:          "https://xszj.org/b/303270",
		SampleChapterURL:        "https://xszj.org/b/303270/c/3520117",
	},
	{
		ID:                      "xhytd",
		Name:                    "黄易天地",
		BaseURL:                 "http://www.xhytd.com",
		BookPatterns:            patterns(commonBookPatterns, numericBookPatterns),
		ChapterPatterns:         patterns(commonChapterPatterns, numericChapterPatterns),
		CatalogSelectors:        []string{"#list > dl > dt:nth-of-type(2) ~ dd > a", "#list dd a"},
		ChapterContentSelectors: []string{"#content"},
		SampleNovelURL:          "http://www.xhytd.com/book/1/",
		SampleChapterURL:        "http://www.xhytd.com/book/1/2.html",
	},
	{
		ID:      "96dushu",
		Name:    "96读书",
		BaseURL: "https://www.96dushu.com",
		BookPatterns: []URLPattern{
			{Expr: `^/book/([^/]+)/?$`, Canonical: `/book/$1/`, BookID: `$1`},
		},
		ChapterPatterns: []URLPattern{
			{Expr: `^/book/([^/]+)/([^/]+)\.html$`, Canonical: `/book/$1/$2.html`, BookID: `$1`, ChapterID: `$2`},
		},
		CatalogSelectors:        []string{"#chapterList > li > a", "#chapterList a"},
		ChapterTitleSelectors:   []string{"#mlfy_main_text > h1"},
		ChapterContentSelectors: []string{"#content"},
		SampleNovelURL:          "https://www.96dushu.com/book/1/",
		SampleChapterURL:        "https://www.96dushu.com/book/1/2.html",
	},
	{
		ID:                      "dongtanxs",
		Name:                    "东滩小说",
		BaseURL:                 "http://www.dongtanxs.com",
		BookPatterns:            patterns(commonBookPatterns, numericBookPatterns),
		ChapterPatterns:         patterns(commonChapterPatterns, numericChapterPatterns),
		CatalogSelectors:        []string{"dl > dt:nth-of-type(2) ~ dd > a", "#list dd a"},
		ChapterTitleSelectors:   []string{".content > h1"},
		ChapterContentSelectors: []string{"#content"},
		SampleNovelURL:          "http://www.dongtanxs.com/book/1/",
		SampleChapterURL:        "http://www.dongtanxs.com/book/1/2.html",
	},
}

func patterns(parts ...[]URLPattern) []URLPattern {
	var out []URLPattern
	for _, part := range parts {
		out = append(out, part...)
	}
	return out
}
