package config

import "wx_channel/pkg/configapi"

// legacy_config_declaration temporarily preserves schemas whose owning
// modules have not been migrated yet.
var legacy_config_declaration = configapi.DeclareModule("legacy",
	configapi.Item{
		Key:         "admin.hostname",
		Type:        configapi.TypeString,
		Default:     "127.0.0.1",
		Description: "指定 GUI/Admin 服务的主机名",
		Title:       "Admin 服务主机",
		Group:       "Admin",
	},
	configapi.Item{
		Key:         "admin.port",
		Type:        configapi.TypeInt,
		Default:     2021,
		Description: "指定 GUI/Admin 服务的端口",
		Title:       "Admin 服务端口",
		Group:       "Admin",
	},

	configapi.Item{
		Key:         "sandbox.dockerImage",
		Type:        configapi.TypeString,
		Default:     "lscr.io/linuxserver/chromium:latest",
		Description: "浏览器沙箱 Docker 镜像，默认使用带 Web 桌面的 Chromium 镜像",
		Title:       "沙箱镜像",
		Group:       "Sandbox",
	},
	configapi.Item{
		Key:         "sandbox.dockerEntrypoint",
		Type:        configapi.TypeString,
		Default:     "",
		Description: "浏览器沙箱 Docker --entrypoint；默认留空以使用 webtop 镜像自己的桌面启动流程",
		Title:       "沙箱 Entrypoint",
		Group:       "Sandbox",
	},
	configapi.Item{
		Key:         "sandbox.dockerNetwork",
		Type:        configapi.TypeString,
		Default:     "",
		Description: "浏览器沙箱 Docker 网络，留空使用默认网络",
		Title:       "沙箱网络",
		Group:       "Sandbox",
	},
	configapi.Item{
		Key:         "sandbox.cdpPortMin",
		Type:        configapi.TypeInt,
		Default:     39222,
		Description: "浏览器沙箱 CDP 宿主机端口范围起点",
		Title:       "CDP 端口起点",
		Group:       "Sandbox",
	},
	configapi.Item{
		Key:         "sandbox.cdpPortMax",
		Type:        configapi.TypeInt,
		Default:     39322,
		Description: "浏览器沙箱 CDP 宿主机端口范围终点",
		Title:       "CDP 端口终点",
		Group:       "Sandbox",
	},
	configapi.Item{
		Key:         "sandbox.desktopPortMin",
		Type:        configapi.TypeInt,
		Default:     39000,
		Description: "浏览器沙箱 Web 桌面宿主机端口范围起点",
		Title:       "桌面端口起点",
		Group:       "Sandbox",
	},
	configapi.Item{
		Key:         "sandbox.desktopPortMax",
		Type:        configapi.TypeInt,
		Default:     39122,
		Description: "浏览器沙箱 Web 桌面宿主机端口范围终点",
		Title:       "桌面端口终点",
		Group:       "Sandbox",
	},
	configapi.Item{
		Key:         "sandbox.resolution",
		Type:        configapi.TypeString,
		Default:     "1920x1080x24",
		Description: "浏览器沙箱 Web 桌面分辨率",
		Title:       "桌面分辨率",
		Group:       "Sandbox",
	},
	configapi.Item{
		Key:         "sandbox.shmSize",
		Type:        configapi.TypeString,
		Default:     "1g",
		Description: "浏览器沙箱 Docker --shm-size",
		Title:       "共享内存",
		Group:       "Sandbox",
	},
	configapi.Item{
		Key:         "sandbox.memoryLimit",
		Type:        configapi.TypeString,
		Default:     "",
		Description: "浏览器沙箱 Docker --memory，留空不限制",
		Title:       "内存限制",
		Group:       "Sandbox",
	},
	configapi.Item{
		Key:         "sandbox.chromeCommand",
		Type:        configapi.TypeText,
		Default:     "",
		Description: "浏览器沙箱容器启动命令，留空时自动查找 Chrome/Chromium 并启用 0.0.0.0:9222 remote debugging",
		Title:       "Chrome 启动命令",
		Group:       "Sandbox",
	},
	configapi.Item{
		Key:         "cloudflare.accountId",
		Type:        configapi.TypeString,
		Default:     "",
		Description: "Cloudflare 帐号 ID",
		Title:       "Account ID",
		Group:       "Cloudflare",
		Reload:      configapi.ReloadHot,
	},
	configapi.Item{
		Key:         "cloudflare.apiToken",
		Type:        configapi.TypeString,
		Default:     "",
		Description: "Cloudflare Worker 认证 Token",
		Title:       "API Token",
		Group:       "Cloudflare",
		Sensitive:   true,
		Reload:      configapi.ReloadHot,
	},
	configapi.Item{
		Key:         "cloudflare.refreshToken",
		Type:        configapi.TypeString,
		Default:     "",
		Description: "调用 mp-rss 凭证刷新接口所需的 token",
		Title:       "Refresh Token",
		Group:       "Cloudflare",
		Sensitive:   true,
		Reload:      configapi.ReloadHot,
	},
	configapi.Item{
		Key:         "cloudflare.adminToken",
		Type:        configapi.TypeString,
		Default:     "",
		Description: "调用 mp-rss 管理员接口所需的凭证",
		Title:       "Admin Token",
		Group:       "Cloudflare",
		Sensitive:   true,
		Reload:      configapi.ReloadHot,
	},
	configapi.Item{
		Key:         "cloudflare.workerName",
		Type:        configapi.TypeString,
		Default:     "official-account-api",
		Description: "Cloudflare mp-rss Worker 名称",
		Title:       "Worker Name",
		Group:       "Cloudflare",
		Reload:      configapi.ReloadHot,
	},
	configapi.Item{
		Key:         "cloudflare.d1Id",
		Type:        configapi.TypeString,
		Default:     "",
		Description: "Cloudflare mp-rss d1数据库 ID",
		Title:       "D1 Database ID",
		Group:       "Cloudflare",
		Reload:      configapi.ReloadHot,
	},
	configapi.Item{
		Key:         "cloudflare.d1Name",
		Type:        configapi.TypeString,
		Default:     "",
		Description: "Cloudflare mp-rss d1数据库 Name",
		Title:       "D1 Database Name",
		Group:       "Cloudflare",
		Reload:      configapi.ReloadHot,
	},
	// Update auto-update configuration
	configapi.Item{
		Key:         "update.proxy",
		Type:        configapi.TypeString,
		Default:     "",
		Description: "update 命令从 GitHub 下载更新时使用的代理地址（如 http://127.0.0.1:7890），与 proxy.upstreamProxy 不同",
		Title:       "更新代理",
		Group:       "Update",
		Reload:      configapi.ReloadHot,
	},
	configapi.Item{
		Key:         "update.mirror",
		Type:        configapi.TypeString,
		Default:     "",
		Description: "update 命令从 GitHub 下载更新时使用的镜像地址（如 https://ghproxy.com/），会拼接在原始 URL 之前",
		Title:       "更新镜像",
		Group:       "Update",
		Reload:      configapi.ReloadHot,
	},
)
